# Generated by Django 4.1.2 on 2022-11-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"verbose_name": "Вакансия", "verbose_name_plural": "Вакансии"},
        ),
    ]
